# Generated by Django 4.2.11 on 2024-07-02 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid_change_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
